lib/config.yml, lib/rubocop-aha/version.rb
* `Style/Documentation` wants every module/class to start with a doc comment. This is not a pattern we've ever followed.
* `Style/FrozenStringLiteralComment` is annoying and we don't use it anywhere, we should tackle that if/when we upgrade to Ruby 3.
=> Disable Style/Documentation and Style/FrozenStringLiteralComment.

lib/config.yml, lib/rubocop-aha/version.rb
Rubocop wants to enforce the following:
```
something.map { |s| s.upcase }
something.map(&:upcase)
```
Whether or not we like that enforcement (I'm not sure I do), it unfortunately causes issues when block parameters are optionally provided. In other words, if the `s` parameter above, is only optionally provided when specified, then the second form will throw an `ArgumentError: no receiver given`.
Googling netted someone with the same experience [here](https://github.com/thoughtbot/factory_girl/issues/698)
I think we should just leave this transformation up to our own judgement, especially given that it can force us to write a line which fails at run time.
=> Disable Style/SymbolProc cop

lib/config.yml, lib/rubocop-aha/version.rb
Rubocop wants us to keep nesting within specs to a max of 3 levels. I agree that avoiding too much nesting is good because it can lead to a hard to understand spec, but I think 3 is just a bit too low. I've run into this cop multiple times and I felt it actually made the specs a little worse after flattening them out.
I'd like to bump it up just a little to 4. It allows for a typical structure like:
```
describe Something do # level 1
context "#some_method" do # level 2
context "some situation" do # level 3
context "some sub situation do # level 4 - this currently isn't allowed
it ...
end
end
end
end
```
I think it's common enough to have some kind of "sub situation" like this that would make it nice to be able to make another level of context nesting to organize it. I can also see that …
=> Increase RSpec/NestedGroups [Max] to 4

lib/config.yml, lib/rubocop-aha/version.rb
* Disable Layout/TrailingWhitespace as we've decided that the cost of polluted blames is not worth the benefit of fixing existing violations.
* Set Style/ClassAndModuleChildren to compact to better match our existing code. Enforces the following:
```ruby
module SomeModule
class SomeClass
end
end
class SomeModule::SomeClass
end
```
* Move Style/EachWithObject into alphabetical position
=> Disable Layout/TrailingWhitespace, set Style/ClassAndModuleChildren to compact

lib/config.yml, lib/rubocop-aha/version.rb
[Aha feature](https://big.aha.io/features/APP-5295)
`RSpec/PredicateMatcher` enforces `expect(object) to
be_boolean_attribute` instead of `expect(object.boolean_attribute?)`
This reads better with some of the Ruby built-ins, but makes Rails'
auto-generated boolean fields read worse. We shouldn't have a strict
preference for style for this one.
=> Disable the RSpec/PredicateMatcher

lib/config.yml, lib/rubocop-aha/version.rb
The default wants:
```ruby
a = ->(x, y) { x + y }
```
This change instead enforces:
```ruby
a = -> (x, y) { x + y }
```
which is how the vast majority of our existing lambdas are spaced.
=> Configure Layout/SpaceInLambdaLiteral to require_space

lib/config.yml
This cop seems to just prefer using guard statements inside of blocks instead of if statements. Seemed worth disabling—we have enough discretion to know what to use.
This cop tried to force this:
```ruby
if epic.save && epic_params[:move_to_release] == "true"
epic.features.each do |feature|
feature.update_attribute(:release_id, release_id)
end
end
```
Into this:
```ruby
next unless epic.save && epic_params[:move_to_release] == "true"
epic.features.each do |feature|
feature.update_attribute(:release_id, release_id)
end
```
=> Disable Style/Next

lib/config.yml
Reference: http://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Performance/Casecmp
=> disabling the casecmp cop

lib/config.yml
This rule prevents setting up test spies & method stubs in before blocks.
Test setup like this should be possible without repeating in every example:
```
before do
expect(subject).to_not receive(:external_api_call)
end
it "does other stuff" do
end
```
=> Allow setting up mocks in before blocks

lib/config.yml, lib/rubocop-aha/version.rb
Disable style requiring `[:a, :b, :c]` to be `%i(a b c)`
It seems like people prefer to use symbol arrays when they are small and I don't think the %i() syntax makes life any better.
=> Disable the symbol array check

lib/config.yml, lib/rubocop-aha/version.rb
I'm surprised that we've avoided this one so far. Here's the documentation: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/NumericLiterals
I don't see any point in keeping this. It recently complained about a line where I hardcoded an ID in a spec. For example:
`expect(id).to eq 12345`
would need to be changed to:
`expect(id).to eq 12_345`
Yeah, no.
=> disable Style/NumericLiterals cop

lib/config.yml
IMO it is not a good practice to enforce language with superfluous words
which is contextual (hah) and not correctable.
=> Disable RSpec/ContextWording

lib/config.yml
#27 had this defined under `Style` and it was giving warnings although it was recognized.
=> Correct namespace for rule

lib/config.yml
(Rails itself also has several methods that just take an "options" hash...)
We should use our judgment on what is too many parameters, but this should not
restrict us when it does make sense to have named options on helper methods.
This is also a solution for something I couldn't resolve: pronto is complaining about this on a couple spec helper methods, but rubocop doesn’t see the same failure in CI. Adding a `rubocop:disable` for this just causes it to complain the other way that it's an "unnecessary disabling".
There might be a more fundamental configuration fix to get these tools to agree, but after discussing this it sounds like we could just disable it. Instead of fully disabling it, ~this just allows for named arguments instead.~
EDIT: this now allows for unlimited positional …
=> Allow for methods with more keyword arguments

lib/config.yml
Don't enforce a particular style for block delimiters, whether single- or multi-
line. This allows for better readability when chaining blocks, and consistency
when defining a group of DSL blocks (e.g. rspec `let` when some are single- and
others are multi-line).
Follows from the discussion in #18.
=> Allow for block delimiters that make sense based on context

lib/config.yml
Using `described_class` instead of the actual class name is often unnecessary,
unless you actually need to metaprogram your tests. This makes things harder to
search for and understand at a glance.
(Also, sometimes it's a module and not a class.)
=> Avoid being more abstract than necessary in RSpec

lib/config.yml
StandardError exists in ruby as a default baseline for rescuing errors and
shouldn't need to be specified when you just want to rescue anything.
Classes outside of StandardError are system errors, which shouldn't ever be
rescued unless you really know what you're doing. These should be specified only
when absolutely needed.
Subclasses of StandardError are more specific types of application errors
that may be specified when needed.
Requiring an exception class to be named for every rescue block means giving up
the convention of a default baseline for normally-rescuable errors.
Hence, exception classes should only be specified when they are meaningful:
when it is known that only specific types of errors should be rescued, and only
then be highlighted as such.
=> Don't specify StandardError when you mean "all reasonable errors"

lib/config.yml
The nested style allows deeply-nested modules to be reopened and still access
other constants that are declared in the same namespace without needing to use
absolute `::` top-level addressing:
module TopLevel
Base = Class.new
end
module TopLevel
class SecondLevel < Base  # instead of ::TopLevel::Base
end
end
The compact style is useful when the expected nesting is already loaded and
defined, so the types of the nesting objects don't need to be re-declared:
class Example < ActiveModel::Base
end
module Example::Helpers
end
Sometimes a combination is warranted, with the top-level namespace module
explicitly defined as a catch-all for constant lookup. The rules for declaring a
new object under a Module vs. a Class should not be enforced differently.
=> Don't enforce style of module declaration

lib/config.yml
This rule is already disabled in aha-services-2, so this is an attempt to standardize our rules between repositories.
When a statement is shown as one long line, it is often more readable to have
the condition stated separately, up front, instead of having to look over to the
end of a long line.
It may also help to break up complex statements into one condition line, and one
statement line for easier debugging.
This leaves it up to the author's discretion whether a condition makes more
sense as a trailing modifier or a block based on context.
=> Don't enforce if/unless to be used as a trailing modifier

lib/config.yml
Reverts aha-app/rubocop-aha#33
Two things:
1. We need to update the app for rubocop to pass or update, and I’m not sure we should now.
2. After seeing what it’s asking in practice, I’m not sure about this one and I think it warrants further discussion because I like the idea of being explicitly forced to think about which exception you want to rescue.
=> Revert "Don't specify StandardError when you mean "all reasonable errors""

lib/config.yml
The other layout items for classes and other types of blocks are already
disabled, this makes modules consistent with the rest.
Reason one, this allows for method comments to not be jammed up against the
containing module at the top:
module Example
def example
end
end
Reason two, this allows for separation between nesting levels to spot where
methods vs. modules end at the bottom, instead of having the staircase of `end`s
jammed together:
module Example
module Component
module Functionality
def example
end
end
end
end
=> Disable Layout/EmptyLinesAroundModuleBody

lib/config.yml
We don't do this in JavaScript, why do it in Ruby?
The default here is "no_comma".
Trailing commas can make sense for collection values like hashes and arrays so
that appending values only shows the addition of one line in diffs. However,
method arguments are not something that is typically expected to append more
values, and allowing for infinite arguments is not something we should promote
in our default style.
=> Disable trailing comma in arguments

lib/config.yml
- DescribeClass allows us to just say `describe "something"`
- DescribedClass allows us to use the actual class instead of the meta
`described_class` method and avoid unnecessary abstraction in tests.
=> We want to disable both DescribeClass and DescribedClass

lib/config.yml
It's a common idiom in ruby to use `_` as the name of an unused method parameter, but rubocop by default won't allow this because it's not 3 characters long.
=> Allow using _ as a block or method parameter name.

lib/config.yml, rubocop-aha.gemspec
Updating rubocop-rspec adds some new rules. Not all of them are desirable.
This allows the new [RSpec/ImplicitSubject](https://rubocop-rspec.readthedocs.io/en/latest/cops_rspec/#rspecimplicitsubject) rule for one-liners.
=> Update rubocop-rspec dependency & new rules

lib/config.yml
When the author provides more than one character for a param name, it indicates
that they have at least put some thought into it. This allows more 2 letter
names such as "op", "db", etc.
The override for block param names is removed because the default there is 1
character and it's redundant.
=> Reduce the minimum allowed param length from 3 to 2

lib/config.yml
This was just removed, but apparently rubocop doesn't include `_` as a default allowed param name when defining subclass methods with unused params.
=> The nameless method param `_` still needs to be allowed

lib/config.yml
This is one of those rules that is good to follow as a rule of thumb, but should
not be enforced. It should be possible to write a single-line spec that also has
a description (or including a simple setup) without forcing it on one line:
it "is the answer"
is_expected.to eq 42
end
This is fine. However, please avoid using implicit subject in complex examples
with multiple variables, where the actual subject is unclear from the
surrounding context.
=> Disable RSpec/ImplicitSubject

README.md, lib/config.yml, lib/rubocop-aha/version.rb, rubocop-aha.gemspec
Bump version of rubocop to the latest.
This removes some obsolete rules, and renames some according to upstream.
Here I've defined a versioning strategy for this gem: if we change a rule (either ourselves or from upstream) in a way that is more restrictive on our codebase, the version should be updated appropriately.
=> IM-611 Update rubocop dependency

lib/config.yml
This configures a rule that was recently introduced by rubocop to match another existing rule.
Layout rules for calling & declaring methods should work the same way. This
allows DSL methods to be declared with indented line continuation (2 spaces),
without needing to wrap everything in parentheses.
attr_accessible :one, :two
:three, :four
=> Make new AlignArguments rule work the same as AlignParameters

lib/config.yml
I'd like to call the variable what I want. error, not e
=> Disable RescuedExceptionsVariableName, we already ignore it all over the place

lib/config.yml
It does not change a thing whether we describe our specs with "should" or "must"
or "is expected to". Leave some room for natural language in descriptions.
```
it "should be allowed" do
end
```
=> Allow describing specs as how they "should" behave

lib/config.yml
We use the with() helper which creates context blocks. Rubocop doesn't
detect that these are context blocks, and so it complains about repeated
examples
=> Disable RSpec/RepeatedExample due to clash with

lib/config.yml
In spec directory only, disable warnings for:
> Models should subclass `ApplicationRecord`
Defining an isolated model in the test suite should not require all of
ApplicationRecord. Sometimes we want to unit test ActiveRecord extensions
without requiring our application extras.
In spec directory only, disable warnings for:
> Use a string value for `class_name`
Defining isolated isolated models under a test module should allow us to
reference these ad-hoc classes directly in-place for ActiveRecord associations
without needing to express it as a fully-qualified module string to be loaded.
=> Allow more flexibility to set up test models

lib/config.yml
Often we seem to want to use method_missing and specifically do not want
to call super because all calls are proxied.
=> Disable Style/MethodMissingSuper.

lib/config.yml
This rule is oversensitive and often leads to less readable code. After running it through autofix and looking at the results, it seemed like a step backward. 
How if statements are written should be a call made based on context, and while we should be sensitive to negated ifs, an automated rule isn't the way to do it.
=> Disable Style/NegatedIf

lib/config.yml
Do we need to enforce a style for float division? 
The default is to choose one side only. This could lead to bugs introduced by by unwittingly changing that side to be an integer and leading to an unwanted result. It would be better to require both sides coerced. 
Example failure:
```
xxxxx.rb:68:9: C: Style/FloatDivision: Prefer using .to_f on one side only.
((discount.to_f / total.to_f) * 100).round
```
This PR disables the cop as it seems unnecessary.
https://rubystyle.guide#float-division
By default robocop uses : single_coerce
=> Don't enforce coercion convention for float division

lib/config.yml
I think we should remove Rails/Delegate. The primary reason is that it makes searching for a method definition in a large codebase difficult.
```ruby
def bar
foo.bar
end
delegate :bar to: :foo
```
A potentially more compelling case is that it also makes the prefixed case far more obsure, and significantly harder to find.
```ruby
def foo_bar
foo.bar
end
delegate :bar, to: :foo, prefix: true
```
=> Remove Rails/Delegate

lib/config.yml
The prefixes `get_` and `set_` are not necessarily for object attributes.
- `get` can mean fetching/loading something from a remote resource
- `set` can mean pushing/storing a value
It doesn't make sense to invent aliases for these common procedures. Whether
they are actually attributes or not is irrelevant, and these names should be
allowed where they make sense.
This rule adds no value.
=> Disable Naming/AccessorMethodNames

lib/config.yml, lib/rubocop-aha/version.rb
This is not a particularly important rule, and fixing instances of it in the codebase also makes it harder to know who wrote any existing incorrectly formatted comments. Just...don't search for `TODO:` specifically and everything will be fine.
=> Disable Style/CommentAnnotation

lib/config.yml, lib/rubocop-aha/version.rb
The general consensus appears to be https://github.com/aha-app/rubocop-aha/pull/70 should be disabled, so we should also then disable MultilineArrayBraceLayout.
Link: https://docs.rubocop.org/rubocop/cops_layout.html#layoutmultilinearraybracelayout
=> Disable Layout/MultilineArrayBraceLayout.

lib/config.yml, lib/rubocop-aha/version.rb
We want `Lint/MissingSuper`, not `Lint/MethodMissingSuper`.
https://github.com/rubocop-hq/rubocop/blob/5f27629e438952bdbc05d84cf3951f429ec2556e/config/obsoletion.yml#L76-L79
=> Cn 882 missing super

lib/config.yml, lib/rubocop-aha/version.rb
Disable https://docs.rubocop.org/rubocop-rspec/cops_rspec.html#rspecmultiplememoizedhelpers.
I think this is fairly arbitrary and I'd rather we disable it for now.
=> Fixes CN-883 - Disable RSpec/MultipleMemoizedHelpers.

lib/config.yml, lib/rubocop-aha/version.rb
Pretty sure we will never use windows but arguments allows the underlying system to generate the path correctly. Do not force the developer to write paths.
This does impact absolute paths:
https://github.com/rubocop-hq/rubocop-rails/issues/195#issuecomment-580412005
=> Use arguements in FilePath

lib/config.yml, lib/rubocop-aha/version.rb, rubocop-aha.gemspec
…ocop-rspec-focused dependency.
Upgrade to rubocop 1.1.0.  This also cleans up the gemfile to remove the now very old `rubocop-rspec-focused`, which was [replaced](https://github.com/lovewithfood/rubocop-rspec-focused#rubocop-rspec-focused) by `rubocop-rspec`.
=> Cn 817 upgrade rubocop 1 1 0

lib/config.yml
Not all tasks need to wait for Rails to be loaded.
=> Allow defining tasks without application dependencies
